### ISSUE TITLE
Scenarios is not found

### ISSUE THREAD

**Issue by PAlamirpour** [stephane-caron/dynamic-walking#1]
Hello sir
It is my pleasure to talk to you. I have been compiling your GitHub code. But there is a problem, The Scenarios part has been missed. Would you help me out for solving the issue?

**Comment by stephane-caron** [comment]
Thank you for your report and sorry for this. This is fixed in commit 7adbc8dcb0145ce6602adb4449a7274d2edc53a8; you can checkout the latest commit from master and it should work.

**Comment by PAlamirpour** [comment]
No problem. I appreciate your time and effort. It is fixed.
