### ISSUE TITLE
MPC preview is not updated

### ISSUE THREAD

**Issue by PAlamirpour** [stephane-caron/dynamic-walking#2]
Hello sir
I work on [fip-walking](https://github.com/stephane-caron/fip-walking) and I compiled the source code base on the guide which was written in GitHub. I have a problem. There might be a problem in the ZMP calculation part. I have uploaded a [video ](https://youtu.be/ZsthSV1vqf4) about the problem. As you can see, ZMP part goes to infinite value. Would you help me out fix this problem?

**Comment by stephane-caron** [comment]
Judging from your video, the main problem is that your MPC preview is not updated (the fact that the robot diverges after a while is only a consequence, as the system without preview update is numerically unstable). This is most likely a solver error.

I'm not sure your IPOPT installation is working correctly (if it were, you should see a message starting with "This program contains Ipopt..." at the beginning of the simulation, but I don't see it in your video). Can you check that you run the [ipopt.py](https://github.com/casadi/casadi/blob/master/docs/api/examples/solvers/ipopt.py) example from CasADi successfully?

**Comment by PAlamirpour** [comment]
Thank you for your response. I checked the [example](https://github.com/casadi/casadi/blob/master/docs/api/examples/solvers/ipopt.py) of cassadi. It works fine for me. But as you told, The "This program contains Ipopt..." did not appear in the start of [fip-walking](https://github.com/stephane-caron/fip-walking) simulation. I think it is better I'll check all of the imported cassadi libraries and their paths. If I can find the problem's reason, I'll explain here.
