### ISSUE TITLE
CasADi solver keyword

### ISSUE THREAD

**Issue by ghost** [stephane-caron/dynamic-walking#4]
Hello Dr.Caron

I tried to use fip-walking code and I had problem with casadi solver. The solver keyword needs to change from "t_wall_mainloop" to "iter_count". I thought it might be helpful for you.

Cheers,
Mohammad

**Comment by stephane-caron** [comment]
What version of CasADi are you using? Mine is 3.1.1:
```python
In [4]: casadi.__version__
Out[4]: '3.1.1'
```
The only location where I see a "t_wall_mainloop" in the code is in ``pymanoid/pymanoid/thirdparty/casadi_.py``:
```python
    @property
    def solve_time(self):
        """
        Time (in seconds) taken to solve the problem.
        """
        return self.solver.stats()['t_wall_mainloop']
```
It ain't broken on my setup, as I can read the solve time from the CoM NLP solver:
```python
In [5]: wpg.com_mpc.solve_time
Out[5]: 0.008990049362182617
```
If you replace the ``stats()`` index by "iter_count" in the function above, it won't give you the same information (solve time in seconds).
